version: '3'
services:
    app:
        build: .
        image: medic-hospital
        container_name: medic-hospital-app
        restart: unless-stopped
        environment:
          DB_HOST: db
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        networks:
            - medic-hospital
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: medic-hospital-nginx
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80
        networks:
            - medic-hospital
        depends_on:
            - app
            - db

    db:
        image: mysql:5.7
        container_name: medic-hospital-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - medic-hospital-db:/var/lib/mysql
        ports:
          - 3306:3306
        networks:
            - medic-hospital

networks:
    medic-hospital:
        driver: bridge

volumes:
    medic-hospital-db:
        driver: local
